In [1]:
import tensorflow as tf
tf.test.gpu_device_name()

'/device:GPU:0'

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import os
import cv2
from numpy import expand_dims
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
from keras.preprocessing.image import ImageDataGenerator
from matplotlib import pyplot

In [3]:
new_model = tf.keras.models.load_model("D:/Modelos/EfficientNet_B1_IMAGENET_IC_SCM3")

In [4]:
new_model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
efficientnetb1 (Functional)  (None, 1, 1, 1280)        6575239   
_________________________________________________________________
global_average_pooling2d (Gl (None, 1280)              0         
_________________________________________________________________
flatten (Flatten)            (None, 1280)              0         
_________________________________________________________________
dropout (Dropout)            (None, 1280)              0         
_________________________________________________________________
dense (Dense)                (None, 4)                 5124      
Total params: 6,580,363
Trainable params: 6,518,308
Non-trainable params: 62,055
_________________________________________________________________


In [5]:
#carrega os arrays de imagens e de classes
train_X = np.load("D:/Displasia/displasiaDataAug/displasiaOriginalDataX_teste3.npy")
train_label = np.load("D:/Displasia/displasiaDataAug/displasiaOriginalDataYOneHot_teste3.npy")
XSCM = np.load("D:/Displasia/displasiaDataAug/displasiaOriginalDataX_teste3_GLCM.npy")
#dataX = np.load("Image Arrays/displasiaGeneratedDataX.npy")
#dataY = np.load("Image Arrays/displasiaGeneratedDataY.npy")

#shape dos arrays
train_X.shape, train_label.shape

((75776, 32, 32, 3), (75776, 4))

In [8]:
from sklearn import metrics
from sklearn.ensemble import RandomForestClassifier
import keras
from sklearn.model_selection import KFold
#kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=7)
kfold = KFold(n_splits=5, shuffle=True, random_state=7)
cvscores = []

mean = [[[],[],[],[],[]],
         [[],[],[],[],[]],
         [[],[],[],[],[]],
         [[],[],[],[],[]]]

std = [[[],[],[],[],[]],
         [[],[],[],[],[]],
         [[],[],[],[],[]],
         [[],[],[],[],[]]]

for train, test in kfold.split (train_X, train_label):

    intermediate_layer_model = keras.Model(inputs=new_model.input,
                                           outputs=new_model.get_layer('flatten').output)
    intermediate_output = intermediate_layer_model.predict(train_X[train])

    newArr = np.append(intermediate_output, XSCM[train] , axis=1)

    clf=RandomForestClassifier(n_estimators=100)
    #train_labels2=train_labels[:49984]
    clf.fit(newArr,train_label[train])

    intermediate_layer_model_2 = keras.Model(inputs=new_model.input,
                                           outputs=new_model.get_layer('flatten').output)
    intermediate_output_2 = intermediate_layer_model_2.predict(train_X[test])

    newArr_test = np.append(intermediate_output_2, XSCM[test] , axis=1)

    y_pred=clf.predict(newArr_test)

    # Model Accuracy, how often is the classifier correct?
    print("Accuracy:",metrics.accuracy_score(train_label[test], y_pred))
    cvscores.append(metrics.accuracy_score(train_label[test], y_pred)*100)
    
    from keras.utils import to_categorical

    predicted_classes = y_pred

    predicted_classes = np.argmax(np.round(predicted_classes),axis=1)

    predicted_classes = to_categorical(predicted_classes)

    
    num_classes = 4
    from sklearn.metrics import classification_report
    target_names = ["Class {}".format(i) for i in range(num_classes)]
    print(classification_report(train_label[test], predicted_classes, target_names=target_names))
    
    from sklearn.metrics import confusion_matrix

    #converte os arrays de classe de one-hot para númerico
    test_label_aux = np.argmax(train_label[test], axis=1)
    predicted_classes = np.argmax(predicted_classes, axis=1)

    #gera a matriz de confusão a partir da predição feita
    cm = confusion_matrix(test_label_aux, predicted_classes)

    #gera os valores de falso positivo, falso negativo, verdadeiro positivo e verdadeiro negativo
    fp = cm.sum(axis=0) - np.diag(cm)  
    fn = cm.sum(axis=1) - np.diag(cm)
    tp = np.diag(cm)
    tn = cm.sum() - (fp + fn + tp)

    #gera a sensitividade, especificidade, acurácia e precisão
    sensitivity = tp / (tp + fn)
    specificity = tn / (tn + fp)
    accuracy    = (tp + tn) / (tp + tn + fp + fn)
    precision   = tp / (tp + fp)
    f1_score = 2/((1/precision)+(1/sensitivity))

    #mostra os resultados
    print("Precision:  ", precision)
    print("Sensitivity:", sensitivity)
    print("Specificity:", specificity)
    print("F1-score:   ", f1_score)
    print("Accuracy:   ", accuracy)
    
    x = []
    x.append(precision)
    x.append(sensitivity)
    x.append(specificity)
    x.append(f1_score)
    x.append(accuracy)
    
    x = np.asarray(x)
    
    x = x.transpose()
    print()
    print(x)
    
    for i in range(4):
        for j in range(5):
            mean[i][j].append(x[i][j])
            std[i][j].append(x[i][j])
    
print("%.2f%% (+/- %.2f%%)" %(np.mean(cvscores),np.std(cvscores)))


Accuracy: 0.9982845077856954
              precision    recall  f1-score   support

     Class 0       1.00      1.00      1.00      3867
     Class 1       1.00      1.00      1.00      3755
     Class 2       1.00      1.00      1.00      3686
     Class 3       1.00      1.00      1.00      3848

   micro avg       1.00      1.00      1.00     15156
   macro avg       1.00      1.00      1.00     15156
weighted avg       1.00      1.00      1.00     15156
 samples avg       1.00      1.00      1.00     15156

Precision:   [0.99948307 0.99680426 0.99728703 0.99947998]
Sensitivity: [1.         0.99680426 0.99728703 0.9989605 ]
Specificity: [0.99982284 0.99894746 0.99912816 0.99982313]
F1-score:    [0.99974147 0.99680426 0.99728703 0.99922017]
Accuracy:    [0.99986804 0.99841647 0.99868039 0.99960412]

[[0.99948307 1.         0.99982284 0.99974147 0.99986804]
 [0.99680426 0.99680426 0.99894746 0.99680426 0.99841647]
 [0.99728703 0.99728703 0.99912816 0.99728703 0.99868039]
 [0.99947998

In [9]:
mean = np.asarray(mean)
std = np.asarray(std)
for i in mean:
    print(np.mean(i,axis=1))
print()
for i in std:
    print(np.std(i,axis=1))

[0.99931118 0.99978478 0.99977154 0.99954791 0.99977565]
[0.99709791 0.99672846 0.99903207 0.99691286 0.99845598]
[0.99725481 0.99772344 0.99908513 0.99748879 0.99874631]
[0.99915027 0.99857256 0.99971894 0.99886132 0.99943254]

[2.20187133e-04 2.03813158e-04 6.94122670e-05 1.88082807e-04
 8.95079668e-05]
[0.000941   0.00025088 0.00031502 0.00042808 0.00021924]
[0.00067408 0.00081096 0.0002274  0.00052411 0.00025384]
[2.77895676e-04 2.77596835e-04 8.41513824e-05 2.47096114e-04
 1.15056262e-04]
