In [1]:
import tensorflow as tf
tf.test.gpu_device_name()

'/device:GPU:0'

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import os
import cv2
from numpy import expand_dims
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
from keras.preprocessing.image import ImageDataGenerator
from matplotlib import pyplot

In [3]:
new_model = tf.keras.models.load_model("D:/Modelos/ResNet50_IC_copy")

In [4]:
new_model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
resnet50 (Functional)        (None, 1, 1, 2048)        23587712  
_________________________________________________________________
global_average_pooling2d (Gl (None, 2048)              0         
_________________________________________________________________
flatten (Flatten)            (None, 2048)              0         
_________________________________________________________________
dropout (Dropout)            (None, 2048)              0         
_________________________________________________________________
dense (Dense)                (None, 512)               1049088   
_________________________________________________________________
dropout_1 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 4)                 2

In [5]:
#carrega os arrays de imagens e de classes
train_X = np.load("D:/Displasia/displasiaDataAug/displasiaOriginalDataX_teste3.npy")
train_label = np.load("D:/Displasia/displasiaDataAug/displasiaOriginalDataYOneHot_teste3.npy")
XSCM = np.load("D:/Displasia/displasiaDataAug/displasiaOriginalDataX_teste3_GLCM.npy")
#XGLCM = np.load("D:/Displasia/displasiaDataAug/displasiaOriginalDataX_teste3_GLCM.npy")
#dataX = np.load("Image Arrays/displasiaGeneratedDataX.npy")
#dataY = np.load("Image Arrays/displasiaGeneratedDataY.npy")

#XSCM = np.append(XSCM,XGLCM,axis=1)

print(XSCM.shape)

#shape dos arrays
#train_X.shape, train_label.shape
#shape dos arrays
train_X.shape, train_label.shape

(75776, 24)


((75776, 32, 32, 3), (75776, 4))

In [6]:
#from sklearn.model_selection import train_test_split

#divide os dados em 80% para treino e 20% para teste
#train_X, test_X, train_label, test_label = train_test_split(X, Y, test_size=0.2, random_state=13)

#divide os dados de treino em 80% para treino e 20% para validação
#train_X, valid_X, train_label, valid_label = train_test_split(train_X, train_label, test_size=0.2, random_state=13)

#mostra os shapes resultantes das divisões
#print("Training:   ", train_X.shape, train_label.shape)
#print("Validation: ", valid_X.shape, valid_label.shape)
#print("Testing:    ", test_X.shape, test_label.shape)

In [7]:
#divide os dados em 80% para treino e 20% para teste
#train_X_SCM, test_X_SCM, train_label_SCM, test_label_SCM = train_test_split(XSCM, Y, test_size=0.2, random_state=13)

#divide os dados de treino em 80% para treino e 20% para validação
#train_X_SCM, valid_X_SCM, train_label_SCM, valid_label_SCM = train_test_split(train_X_SCM, train_label_SCM, test_size=0.2, random_state=13)

#mostra os shapes resultantes das divisões
#print("Training:   ", train_X_SCM.shape, train_label_SCM.shape)
#print("Validation: ", valid_X.shape, valid_label.shape)
#print("Testing:    ", test_X_SCM.shape, test_label_SCM.shape)

In [8]:
from sklearn import metrics
from sklearn.ensemble import RandomForestClassifier
import keras
from sklearn.model_selection import KFold
#kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=7)
kfold = KFold(n_splits=5, shuffle=True, random_state=7)
cvscores = []

mean = [[[],[],[],[],[]],
         [[],[],[],[],[]],
         [[],[],[],[],[]],
         [[],[],[],[],[]]]

std = [[[],[],[],[],[]],
         [[],[],[],[],[]],
         [[],[],[],[],[]],
         [[],[],[],[],[]]]

for train, test in kfold.split (train_X, train_label):

    intermediate_layer_model = keras.Model(inputs=new_model.input,
                                           outputs=new_model.get_layer('flatten').output)
    intermediate_output = intermediate_layer_model.predict(train_X[train])

    newArr = np.append(intermediate_output, XSCM[train] , axis=1)

    clf=RandomForestClassifier(n_estimators=100)
    #train_labels2=train_labels[:49984]
    clf.fit(newArr,train_label[train])

    intermediate_layer_model_2 = keras.Model(inputs=new_model.input,
                                           outputs=new_model.get_layer('flatten').output)
    intermediate_output_2 = intermediate_layer_model_2.predict(train_X[test])

    newArr_test = np.append(intermediate_output_2, XSCM[test] , axis=1)

    y_pred=clf.predict(newArr_test)

    # Model Accuracy, how often is the classifier correct?
    print("Accuracy:",metrics.accuracy_score(train_label[test], y_pred))
    cvscores.append(metrics.accuracy_score(train_label[test], y_pred)*100)
    
    from keras.utils import to_categorical

    predicted_classes = y_pred

    predicted_classes = np.argmax(np.round(predicted_classes),axis=1)

    predicted_classes = to_categorical(predicted_classes)

    
    num_classes = 4
    from sklearn.metrics import classification_report
    target_names = ["Class {}".format(i) for i in range(num_classes)]
    print(classification_report(train_label[test], predicted_classes, target_names=target_names))
    
    from sklearn.metrics import confusion_matrix

    #converte os arrays de classe de one-hot para númerico
    test_label_aux = np.argmax(train_label[test], axis=1)
    predicted_classes = np.argmax(predicted_classes, axis=1)

    #gera a matriz de confusão a partir da predição feita
    cm = confusion_matrix(test_label_aux, predicted_classes)

    #gera os valores de falso positivo, falso negativo, verdadeiro positivo e verdadeiro negativo
    fp = cm.sum(axis=0) - np.diag(cm)  
    fn = cm.sum(axis=1) - np.diag(cm)
    tp = np.diag(cm)
    tn = cm.sum() - (fp + fn + tp)

    #gera a sensitividade, especificidade, acurácia e precisão
    sensitivity = tp / (tp + fn)
    specificity = tn / (tn + fp)
    accuracy    = (tp + tn) / (tp + tn + fp + fn)
    precision   = tp / (tp + fp)
    f1_score = 2/((1/precision)+(1/sensitivity))

    #mostra os resultados
    print("Precision:  ", precision)
    print("Sensitivity:", sensitivity)
    print("Specificity:", specificity)
    print("F1-score:   ", f1_score)
    print("Accuracy:   ", accuracy)
    
    x = []
    x.append(precision)
    x.append(sensitivity)
    x.append(specificity)
    x.append(f1_score)
    x.append(accuracy)
    
    x = np.asarray(x)
    
    x = x.transpose()
    print()
    print(x)
    
    for i in range(4):
        for j in range(5):
            mean[i][j].append(x[i][j])
            std[i][j].append(x[i][j])
    
print("%.2f%% (+/- %.2f%%)" %(np.mean(cvscores),np.std(cvscores)))


Accuracy: 0.95460543679071
              precision    recall  f1-score   support

     Class 0       0.93      0.99      0.96      3867
     Class 1       0.95      0.94      0.94      3755
     Class 2       0.97      0.94      0.95      3686
     Class 3       0.99      0.95      0.97      3848

   micro avg       0.96      0.96      0.96     15156
   macro avg       0.96      0.96      0.96     15156
weighted avg       0.96      0.96      0.96     15156
 samples avg       0.96      0.96      0.96     15156

Precision:   [0.92864054 0.94563471 0.96844457 0.98624224]
Sensitivity: [0.99275924 0.94034621 0.9408573  0.95010395]
Specificity: [0.97386837 0.98219454 0.99014821 0.99548992]
F1-score:    [0.95963005 0.94298304 0.95445163 0.96783587]
Accuracy:    [0.97868831 0.97182634 0.97816046 0.98396675]

[[0.92864054 0.99275924 0.97386837 0.95963005 0.97868831]
 [0.94563471 0.94034621 0.98219454 0.94298304 0.97182634]
 [0.96844457 0.9408573  0.99014821 0.95445163 0.97816046]
 [0.98624224 0

In [9]:
mean = np.asarray(mean)
std = np.asarray(std)
for i in mean:
    print(np.mean(i,axis=1))
print()
for i in std:
    print(np.std(i,axis=1))

[0.92645239 0.99085932 0.97380324 0.95757104 0.97806693]
[0.94505217 0.93924258 0.98178631 0.94213108 0.97115181]
[0.97045004 0.93838958 0.99048143 0.95414699 0.97745987]
[0.9841235  0.95436709 0.99488452 0.9690103  0.98474452]

[0.00376701 0.00138453 0.0008643  0.00241466 0.00093949]
[0.00283288 0.00416427 0.00113181 0.00241469 0.00128471]
[0.00211877 0.00366183 0.00061582 0.00240205 0.00109847]
[0.00332623 0.00227853 0.00097604 0.00126847 0.00054924]
